# Generated by Django 4.1.4 on 2025-08-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('serial', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PC', 'Computador de Escritorio'), ('LAPTOP', 'Portátil'), ('SERVIDOR', 'Servidor'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_del_pc', models.ImageField(blank=True, null=True, upload_to='fotos_pc/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procesador', models.CharField(max_length=100)),
                ('ram_gb', models.CharField(max_length=100)),
                ('almacenamiento_gb', models.CharField(max_length=100)),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('usuario_asignado', models.CharField(max_length=100)),
                ('contraseña_asignado', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto_historial', models.ImageField(blank=True, null=True, upload_to='fotos_historial/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='PC.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
