# Generated by Django 4.1.4 on 2025-08-06 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
        ('PC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='almacenamiento_gb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='ram_gb',
            field=models.CharField(max_length=100),
        ),
    ]
