# Generated by Django 4.1.4 on 2025-08-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
        ('PC', '0002_equipo_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa'),
        ),
    ]
