# Generated by Django 4.1.4 on 2025-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0003_alter_equipo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='foto_del_pc',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pc/'),
        ),
    ]
