# Generated by Django 4.1.4 on 2025-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC', '0004_equipo_foto_del_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialequipo',
            name='foto_historial',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_historial/'),
        ),
    ]
