# Generated by Django 4.1.4 on 2025-09-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_empresa_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
